#pragma once

// =============================================================================
// GENERATED CARD CONFIG CONTRACT - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

constexpr const char *CARD_CONTRACT_OPTION_SELECT_ACTION = "input_select.select_option";
inline const char *const CARD_CONTRACT_OPTION_SELECT_ACTIONS[] = {"input_select.select_option", "select.select_option"};
inline const char *const CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES[] = {"slider", "light_brightness", "fan_speed"};
inline const char *const CARD_CONTRACT_COVER_MODES[] = {"", "tilt", "toggle", "open", "close", "stop", "set_position"};
inline const char *const CARD_CONTRACT_GARAGE_MODES[] = {"", "open", "close"};
inline const char *const CARD_CONTRACT_GARAGE_LABEL_DISPLAY_MODES[] = {"label", "status"};
inline const char *const CARD_CONTRACT_INTERNAL_MODES[] = {"switch", "push"};
inline const char *const CARD_CONTRACT_LOCK_MODES[] = {"", "lock", "unlock"};
inline const char *const CARD_CONTRACT_MEDIA_MODES[] = {"play_pause", "previous", "next", "volume", "position", "now_playing"};
inline const char *const CARD_CONTRACT_MEDIA_DISPLAY_MODES[] = {"", "state"};
inline const char *const CARD_CONTRACT_MEDIA_NOW_PLAYING_CONTROLS[] = {"", "progress", "play_pause"};
inline const char *const CARD_CONTRACT_MEDIA_LEGACY_MODES[] = {"controls"};
inline const char *const CARD_CONTRACT_MEDIA_STATE_DISPLAY_MODES[] = {"play_pause", "position"};
inline const char *const CARD_CONTRACT_ALARM_ACTION_MODES[] = {"away", "home", "disarm"};
inline const char *const CARD_CONTRACT_ALARM_ICON_DISPLAY_MODES[] = {"static", "status"};
inline const char *const CARD_CONTRACT_ALARM_LABEL_DISPLAY_MODES[] = {"name", "status"};
inline const char *const CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_MODES[] = {"label", "status", "actual", "target"};
inline const char *const CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_MODES[] = {"icon", "actual", "target"};
inline const char *const CARD_CONTRACT_CLIMATE_PRECISION_VALUES[] = {"", "1", "2", "3"};
inline const char *const CARD_CONTRACT_WEATHER_FORECAST_PRECISIONS[] = {"today", "tomorrow"};
constexpr const char *CARD_CONTRACT_GARAGE_LABEL_DISPLAY_DEFAULT = "label";
constexpr const char *CARD_CONTRACT_MEDIA_DEFAULT_MODE = "play_pause";
constexpr const char *CARD_CONTRACT_ALARM_ICON_DISPLAY_DEFAULT = "status";
constexpr const char *CARD_CONTRACT_ALARM_LABEL_DISPLAY_DEFAULT = "status";
constexpr const char *CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_DEFAULT = "label";
constexpr const char *CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_DEFAULT = "target";

inline bool card_contract_string_in(const std::string &value, const char *const *items, size_t count) {
  for (size_t i = 0; i < count; i++) {
    if (value == items[i]) return true;
  }
  return false;
}

inline bool card_contract_is_brightness_slider_type(const std::string &type) {
  return card_contract_string_in(type, CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES,
    sizeof(CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES) / sizeof(CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES[0]));
}

inline bool card_contract_is_option_select_action(const std::string &action) {
  return card_contract_string_in(action, CARD_CONTRACT_OPTION_SELECT_ACTIONS,
    sizeof(CARD_CONTRACT_OPTION_SELECT_ACTIONS) / sizeof(CARD_CONTRACT_OPTION_SELECT_ACTIONS[0]));
}

inline bool card_contract_cover_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_COVER_MODES,
    sizeof(CARD_CONTRACT_COVER_MODES) / sizeof(CARD_CONTRACT_COVER_MODES[0]));
}

inline bool card_contract_garage_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_GARAGE_MODES,
    sizeof(CARD_CONTRACT_GARAGE_MODES) / sizeof(CARD_CONTRACT_GARAGE_MODES[0]));
}

inline bool card_contract_garage_label_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_GARAGE_LABEL_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_GARAGE_LABEL_DISPLAY_MODES) / sizeof(CARD_CONTRACT_GARAGE_LABEL_DISPLAY_MODES[0]));
}

inline bool card_contract_internal_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_INTERNAL_MODES,
    sizeof(CARD_CONTRACT_INTERNAL_MODES) / sizeof(CARD_CONTRACT_INTERNAL_MODES[0]));
}

inline bool card_contract_lock_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_LOCK_MODES,
    sizeof(CARD_CONTRACT_LOCK_MODES) / sizeof(CARD_CONTRACT_LOCK_MODES[0]));
}

inline bool card_contract_media_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_MEDIA_MODES,
    sizeof(CARD_CONTRACT_MEDIA_MODES) / sizeof(CARD_CONTRACT_MEDIA_MODES[0]));
}

inline bool card_contract_media_legacy_mode(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_MEDIA_LEGACY_MODES,
    sizeof(CARD_CONTRACT_MEDIA_LEGACY_MODES) / sizeof(CARD_CONTRACT_MEDIA_LEGACY_MODES[0]));
}

inline bool card_contract_media_state_display_mode(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_MEDIA_STATE_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_MEDIA_STATE_DISPLAY_MODES) / sizeof(CARD_CONTRACT_MEDIA_STATE_DISPLAY_MODES[0]));
}

inline bool card_contract_alarm_action_mode_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_ALARM_ACTION_MODES,
    sizeof(CARD_CONTRACT_ALARM_ACTION_MODES) / sizeof(CARD_CONTRACT_ALARM_ACTION_MODES[0]));
}

inline bool card_contract_alarm_icon_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_ALARM_ICON_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_ALARM_ICON_DISPLAY_MODES) / sizeof(CARD_CONTRACT_ALARM_ICON_DISPLAY_MODES[0]));
}

inline bool card_contract_alarm_label_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_ALARM_LABEL_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_ALARM_LABEL_DISPLAY_MODES) / sizeof(CARD_CONTRACT_ALARM_LABEL_DISPLAY_MODES[0]));
}

inline bool card_contract_climate_label_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_MODES) / sizeof(CARD_CONTRACT_CLIMATE_LABEL_DISPLAY_MODES[0]));
}

inline bool card_contract_climate_number_display_valid(const std::string &mode) {
  return card_contract_string_in(mode, CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_MODES,
    sizeof(CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_MODES) / sizeof(CARD_CONTRACT_CLIMATE_NUMBER_DISPLAY_MODES[0]));
}

inline bool card_contract_climate_precision_valid(const std::string &precision) {
  return card_contract_string_in(precision, CARD_CONTRACT_CLIMATE_PRECISION_VALUES,
    sizeof(CARD_CONTRACT_CLIMATE_PRECISION_VALUES) / sizeof(CARD_CONTRACT_CLIMATE_PRECISION_VALUES[0]));
}

inline bool card_contract_weather_forecast_precision(const std::string &precision) {
  return card_contract_string_in(precision, CARD_CONTRACT_WEATHER_FORECAST_PRECISIONS,
    sizeof(CARD_CONTRACT_WEATHER_FORECAST_PRECISIONS) / sizeof(CARD_CONTRACT_WEATHER_FORECAST_PRECISIONS[0]));
}

inline const char *card_contract_alarm_action_icon_name(const std::string &mode) {
  if (mode == "away") return "Shield Lock";
  if (mode == "home") return "Shield Home";
  if (mode == "disarm") return "Shield Off";
  return "Alarm";
}

inline bool card_contract_alarm_action_legacy_icon_name(const std::string &mode, const std::string &icon) {
  if (mode == "away") return icon == "Security";
  if (mode == "home") return icon == "Home";
  if (mode == "disarm") return icon == "Lock Open";
  return false;
}

inline const char *card_contract_card_label(const std::string &type) {
  if (type == "") return "Switch";
  if (type == "action") return "Action";
  if (type == "alarm") return "Alarm";
  if (type == "alarm_action") return "Alarm";
  if (type == "calendar") return "Date & Time";
  if (type == "climate") return "Climate";
  if (type == "cover") return "Cover";
  if (type == "door_window") return "Doors & Windows";
  if (type == "fan_direction") return "Fans";
  if (type == "fan_oscillate") return "Fans";
  if (type == "fan_preset") return "Fans";
  if (type == "fan_speed") return "Fans";
  if (type == "fan_switch") return "Fans";
  if (type == "garage") return "Garage Door";
  if (type == "internal") return "Internal Switches";
  if (type == "light_brightness") return "Lights";
  if (type == "light_switch") return "Lights";
  if (type == "light_temperature") return "Lights";
  if (type == "lock") return "Lock";
  if (type == "media") return "Media";
  if (type == "option_select") return "Option Select";
  if (type == "push") return "Trigger";
  if (type == "sensor") return "Sensor";
  if (type == "slider") return "Slider";
  if (type == "subpage") return "Subpage";
  if (type == "timezone") return "Date & Time";
  if (type == "weather") return "Weather";
  if (type == "weather_forecast") return "Weather Forecast";
  return type.empty() ? "Switch" : type.c_str();
}

inline bool card_contract_allow_in_subpage(const std::string &type) {
  if (type == "") return true;
  if (type == "action") return true;
  if (type == "alarm") return true;
  if (type == "alarm_action") return true;
  if (type == "calendar") return true;
  if (type == "climate") return true;
  if (type == "cover") return true;
  if (type == "door_window") return true;
  if (type == "fan_direction") return true;
  if (type == "fan_oscillate") return true;
  if (type == "fan_preset") return true;
  if (type == "fan_speed") return true;
  if (type == "fan_switch") return true;
  if (type == "garage") return true;
  if (type == "internal") return true;
  if (type == "light_brightness") return true;
  if (type == "light_switch") return true;
  if (type == "light_temperature") return true;
  if (type == "lock") return true;
  if (type == "media") return true;
  if (type == "option_select") return true;
  if (type == "push") return true;
  if (type == "sensor") return true;
  if (type == "slider") return true;
  if (type == "subpage") return false;
  if (type == "timezone") return true;
  if (type == "weather") return true;
  if (type == "weather_forecast") return true;
  return false;
}

inline const char *card_contract_default_icon_name(const std::string &type) {
  if (type == "") return "Auto";
  if (type == "action") return "Flash";
  if (type == "alarm") return "Security";
  if (type == "alarm_action") return "Shield Lock";
  if (type == "calendar") return "Auto";
  if (type == "climate") return "Thermostat";
  if (type == "cover") return "Blinds";
  if (type == "door_window") return "Door";
  if (type == "fan_direction") return "Swap Horizontal";
  if (type == "fan_oscillate") return "Fan";
  if (type == "fan_preset") return "Fan Auto";
  if (type == "fan_speed") return "Fan Speed 2";
  if (type == "fan_switch") return "Fan Off";
  if (type == "garage") return "Garage";
  if (type == "internal") return "Power";
  if (type == "light_brightness") return "Lightbulb Outline";
  if (type == "light_switch") return "Lightbulb Outline";
  if (type == "light_temperature") return "Lightbulb";
  if (type == "lock") return "Lock";
  if (type == "media") return "Auto";
  if (type == "option_select") return "Flash";
  if (type == "push") return "Gesture Tap";
  if (type == "sensor") return "Auto";
  if (type == "slider") return "Auto";
  if (type == "subpage") return "Auto";
  if (type == "timezone") return "Auto";
  if (type == "weather") return "Auto";
  if (type == "weather_forecast") return "Auto";
  return "Auto";
}

inline const char *card_contract_default_icon_on_name(const std::string &type) {
  if (type == "") return "Auto";
  if (type == "action") return "Auto";
  if (type == "alarm") return "Auto";
  if (type == "alarm_action") return "Auto";
  if (type == "calendar") return "Auto";
  if (type == "climate") return "Auto";
  if (type == "cover") return "Blinds Open";
  if (type == "door_window") return "Door Open";
  if (type == "fan_direction") return "Auto";
  if (type == "fan_oscillate") return "Auto";
  if (type == "fan_preset") return "Auto";
  if (type == "fan_speed") return "Auto";
  if (type == "fan_switch") return "Fan";
  if (type == "garage") return "Garage Open";
  if (type == "internal") return "Flash";
  if (type == "light_brightness") return "Lightbulb";
  if (type == "light_switch") return "Lightbulb";
  if (type == "light_temperature") return "Auto";
  if (type == "lock") return "Lock Open";
  if (type == "media") return "Auto";
  if (type == "option_select") return "Auto";
  if (type == "push") return "Auto";
  if (type == "sensor") return "Auto";
  if (type == "slider") return "Auto";
  if (type == "subpage") return "Auto";
  if (type == "timezone") return "Auto";
  if (type == "weather") return "Auto";
  if (type == "weather_forecast") return "Auto";
  return "Auto";
}

inline bool card_contract_is_fan_card_type(const std::string &type) {
  return type == "fan_switch" ||
         type == "fan_speed" ||
         type == "fan_oscillate" ||
         type == "fan_direction" ||
         type == "fan_preset";
}

inline const char *card_contract_fan_default_icon_name(const std::string &type) {
  if (type == "fan_switch") return "Fan Off";
  if (type == "fan_speed") return "Fan Speed 2";
  if (type == "fan_oscillate") return "Fan";
  if (type == "fan_direction") return "Swap Horizontal";
  if (type == "fan_preset") return "Fan Auto";
  return "Fan Speed 2";
}

inline const char *card_contract_fan_default_icon_on_name(const std::string &type) {
  if (type == "fan_switch") return "Fan";
  return "Auto";
}

inline bool card_contract_large_numbers_supported(const std::string &type, const std::string &precision) {
  if (type == "sensor") return precision != "text";
  if (type == "weather") return precision == "today" || precision == "tomorrow";
  return type == "calendar" || type == "timezone";
}

inline const char *card_contract_subpage_type_code(const std::string &type) {
  if (type == "action") return "A";
  if (type == "calendar") return "D";
  if (type == "timezone") return "T";
  if (type == "sensor") return "S";
  if (type == "door_window") return "X";
  if (type == "weather") return "W";
  if (type == "weather_forecast") return "F";
  if (type == "option_select") return "U";
  if (type == "fan_switch") return "B";
  if (type == "fan_speed") return "J";
  if (type == "fan_oscillate") return "O";
  if (type == "fan_direction") return "E";
  if (type == "fan_preset") return "Z";
  if (type == "light_brightness") return "V";
  if (type == "light_switch") return "Q";
  if (type == "alarm") return "Y";
  if (type == "alarm_action") return "AA";
  if (type == "slider") return "L";
  if (type == "cover") return "C";
  if (type == "light_temperature") return "N";
  if (type == "garage") return "R";
  if (type == "lock") return "K";
  if (type == "media") return "M";
  if (type == "climate") return "H";
  if (type == "push") return "P";
  if (type == "internal") return "I";
  if (type == "subpage") return "G";
  return type.c_str();
}

inline std::string card_contract_subpage_type_from_code(const std::string &code) {
  if (code == "A") return "action";
  if (code == "D") return "calendar";
  if (code == "T") return "timezone";
  if (code == "S") return "sensor";
  if (code == "X") return "door_window";
  if (code == "W") return "weather";
  if (code == "F") return "weather_forecast";
  if (code == "U") return "option_select";
  if (code == "B") return "fan_switch";
  if (code == "J") return "fan_speed";
  if (code == "O") return "fan_oscillate";
  if (code == "E") return "fan_direction";
  if (code == "Z") return "fan_preset";
  if (code == "V") return "light_brightness";
  if (code == "Q") return "light_switch";
  if (code == "Y") return "alarm";
  if (code == "AA") return "alarm_action";
  if (code == "L") return "slider";
  if (code == "C") return "cover";
  if (code == "N") return "light_temperature";
  if (code == "R") return "garage";
  if (code == "K") return "lock";
  if (code == "M") return "media";
  if (code == "H") return "climate";
  if (code == "P") return "push";
  if (code == "I") return "internal";
  if (code == "G") return "subpage";
  return code;
}
