# =============================================================================
# ICONS - Material Design Icons for buttons and setup screens
# =============================================================================
# http://materialdesignicons.com/cdn/7.4.47/
# Button and setup screens share the same icon font.
# =============================================================================

font:
  # Button icons (52px)
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_48_icons
    size: 48
    bpp: 4
    glyphs: !include icon_glyphs.yaml

substitutions:
  icon_wifi_startup: "\U000F05A9"
  icon_wifi: "\U000F0928"
  icon_ethernet: "\U000F0200"
  icon_cog: "\U000F0493"
  icon_home_assistant: "\U000F07D0"
  icon_progress_clock: "\U000F0996"
  icon_check: "\U000F012C"
  icon_chevron_left: "\U000F0141"
  icon_chevron_right: "\U000F0142"
